CREATE MATERIALIZED VIEW public.all_enriched
TABLESPACE pg_default
AS SELECT import_enriched.direction,
    import_enriched.consignee AS company,
    import_enriched.consignee_inn AS inn,
    import_enriched.shipper_seaport AS seaport,
    import_enriched.seaport_unified,
    import_enriched.country,
    import_enriched.region,
    import_enriched.lat_port,
    import_enriched.long_port,
    import_enriched.year_parsed_on AS year,
    import_enriched.month_parsed_on AS month,
    import_enriched.line,
    import_enriched.container_number,
    import_enriched.teu,
    import_enriched.terminal,
    import_enriched.goods_tnved,
    import_enriched.tnved_group_name,
    import_enriched.container_size,
    import_enriched.container_type
   FROM import_enriched
UNION
 SELECT import_nw_enriched.direction,
    import_nw_enriched.consignee_name AS company,
    import_nw_enriched.consignee_inn AS inn,
    import_nw_enriched.seaport,
    import_nw_enriched.seaport_unified,
    import_nw_enriched.country,
    import_nw_enriched.region,
    import_nw_enriched.lat_port,
    import_nw_enriched.long_port,
    import_nw_enriched.year,
    import_nw_enriched.month,
    import_nw_enriched.line,
    import_nw_enriched.container_number,
    import_nw_enriched.teu,
    import_nw_enriched.terminal,
    import_nw_enriched.tnved_group_id AS goods_tnved,
    import_nw_enriched.tnved_group_name,
    import_nw_enriched.container_size,
    import_nw_enriched.container_type
   FROM import_nw_enriched
UNION
 SELECT import_vsk_enriched.direction,
    import_vsk_enriched.consignee_name AS company,
    import_vsk_enriched.consignee_inn AS inn,
    import_vsk_enriched.seaport,
    import_vsk_enriched.seaport_unified,
    import_vsk_enriched.country,
    import_vsk_enriched.region,
    import_vsk_enriched.lat_port,
    import_vsk_enriched.long_port,
    import_vsk_enriched.year,
    import_vsk_enriched.month,
    import_vsk_enriched.line,
    import_vsk_enriched.container_number,
    import_vsk_enriched.teu,
    import_vsk_enriched.terminal,
    import_vsk_enriched.tnved_group_id AS goods_tnved,
    import_vsk_enriched.tnved_group_name,
    import_vsk_enriched.container_size,
    import_vsk_enriched.container_type
   FROM import_vsk_enriched
UNION
 SELECT export_enriched.direction,
    export_enriched.shipper AS company,
    export_enriched.shipper_inn AS inn,
    export_enriched.unload_seaport AS seaport,
    export_enriched.seaport_unified,
    export_enriched.country,
    export_enriched.region,
    export_enriched.lat_port,
    export_enriched.long_port,
    export_enriched.year_parsed_on AS year,
    export_enriched.month_parsed_on AS month,
    export_enriched.line,
    export_enriched.container_number,
    export_enriched.teu,
    export_enriched.terminal,
    export_enriched.goods_tnved,
    export_enriched.tnved_group_name,
    export_enriched.container_size,
    export_enriched.container_type
   FROM export_enriched
UNION
 SELECT export_nw_enriched.direction,
    export_nw_enriched.shipper_name AS company,
    export_nw_enriched.shipper_inn AS inn,
    export_nw_enriched.seaport,
    export_nw_enriched.seaport_unified,
    export_nw_enriched.country,
    export_nw_enriched.region,
    export_nw_enriched.lat_port,
    export_nw_enriched.long_port,
    export_nw_enriched.year,
    export_nw_enriched.month,
    export_nw_enriched.line,
    export_nw_enriched.container_number,
    export_nw_enriched.teu,
    export_nw_enriched.terminal,
    export_nw_enriched.tnved_group_id AS goods_tnved,
    export_nw_enriched.tnved_group_name,
    export_nw_enriched.container_size,
    export_nw_enriched.container_type
   FROM export_nw_enriched
UNION
 SELECT export_vsk_enriched.direction,
    export_vsk_enriched.shipper_name AS company,
    export_vsk_enriched.shipper_inn AS inn,
    export_vsk_enriched.seaport,
    export_vsk_enriched.seaport_unified,
    export_vsk_enriched.country,
    export_vsk_enriched.region,
    export_vsk_enriched.lat_port,
    export_vsk_enriched.long_port,
    export_vsk_enriched.year,
    export_vsk_enriched.month,
    export_vsk_enriched.line,
    export_vsk_enriched.container_number,
    export_vsk_enriched.teu,
    export_vsk_enriched.terminal,
    export_vsk_enriched.tnved_group_id AS goods_tnved,
    export_vsk_enriched.tnved_group_name,
    export_vsk_enriched.container_size,
    export_vsk_enriched.container_type
   FROM export_vsk_enriched
WITH DATA;